https://exoplanetarchive.ipac.caltech.edu/cgi-bin/TblView/nph-tblView?app=ExoTbls&config=PSCompPars

Source for Dataset : NASA Exoplanet Archive - Planetary Systems Composite Parameters

In [3]:
import pandas as pd

df = pd.read_csv("NASA Exoplanet dataset.csv", comment='#')
df.head()

,pl_name,hostname,sy_snum,sy_pnum,discoverymethod,disc_year,disc_facility,pl_controv_flag,pl_orbper,pl_orbpererr1,...,sy_disterr2,sy_vmag,sy_vmagerr1,sy_vmagerr2,sy_kmag,sy_kmagerr1,sy_kmagerr2,sy_gaiamag,sy_gaiamagerr1,sy_gaiamagerr2
0,11 Com b,11 Com,2,1,Radial Velocity,2007,Xinglong Station,0,323.21000,0.06000,...,-1.9238,4.72307,0.023,-0.023,2.282,0.346,-0.346,4.44038,0.003848,-0.003848
1,11 UMi b,11 UMi,1,1,Radial Velocity,2009,Thueringer Landessternwarte Tautenburg,0,516.21997,3.20000,...,-1.9765,5.01300,0.005,-0.005,1.939,0.270,-0.270,4.56216,0.003903,-0.003903
2,14 And b,14 And,1,1,Radial Velocity,2008,Okayama Astrophysical Observatory,0,186.76000,0.11000,...,-0.7140,5.23133,0.023,-0.023,2.331,0.240,-0.240,4.91781,0.002826,-0.002826
3,14 Her b,14 Her,1,2,Radial Velocity,2002,W. M. Keck Observatory,0,1765.03890,1.67709,...,-0.0073,6.61935,0.023,-0.023,4.714,0.016,-0.016,6.38300,0.000351,-0.000351
4,16 Cyg B b,16 Cyg B,3,1,Radial Velocity,1996,Multiple Observatories,0,798.50000,1.00000,...,-0.0111,6.21500,0.016,-0.016,4.651,0.016,-0.016,6.06428,0.000603,-0.000603

Planet radius, mass, surface temperature, orbital period, 
distance from star, Host star type, temperature, metallicity are present in the dataset

density, luminosity can be computed

Density = Mass / Volume

In [10]:
import numpy as np

EARTH_DENSITY = 5.51 

df["pl_density"] = (df["pl_bmasse"] / (df["pl_rade"]**3)) * EARTH_DENSITY


df[["pl_name", "pl_density"]].head()

      pl_name  pl_density
0    11 Com b   14.913743
1    11 UMi b   13.871666
2    14 And b    2.772416
3    14 Her b    7.050020
4  16 Cyg B b    1.266967

In [11]:
SUN_TEMP = 5772 
df["st_luminosity"] = (df["st_rad"]**2) * (df["st_teff"] / SUN_TEMP)**4
df[["pl_name", "st_luminosity"]].head()

      pl_name  st_luminosity
0    11 Com b      96.266166
1    11 UMi b     251.884564
2    14 And b      68.609376
3    14 Her b       0.632667
4  16 Cyg B b       1.257543

Schema of dataset

In [12]:
print("ROWS:", df.shape[0])
print("COLUMNS:", df.shape[1])
print("\nCOLUMN TYPES:\n", df.dtypes)
print("\nMISSING VALUES:\n", df.isnull().sum())

ROWS: 6052
COLUMNS: 86

COLUMN TYPES:
 pl_name             object
hostname            object
sy_snum              int64
sy_pnum              int64
discoverymethod     object
                    ...
sy_gaiamag         float64
sy_gaiamagerr1     float64
sy_gaiamagerr2     float64
pl_density         float64
st_luminosity      float64
Length: 86, dtype: object

MISSING VALUES:
 pl_name              0
hostname             0
sy_snum              0
sy_pnum              0
discoverymethod      0
                  ...
sy_gaiamag         325
sy_gaiamagerr1     326
sy_gaiamagerr2     326
pl_density          49
st_luminosity      301
Length: 86, dtype: int64